spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: RIe7rQE0vmJJWI1pw8zihzlS6ZkJNUo6
            client-secret: azjuWPf-AAN5Esqu_6OdpHQajyoAlCK0GAue9UFKxV8awl7-__1GlokR3l2UEHIS
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://dev-m-nyorq5.us.auth0.com/